export const translations = {
  en: {
    title: "Guess the truth before it consumes you...",
    loseTextPrefix: "The truth remains hidden: ",
    allRevealedTitle: "✦ All Secrets Revealed ✦",
    allRevealedText: "You have uncovered all the truths... for now.",

  },
  es: {
    title: "Adivina la verdad antes de que te consuma...",
    loseTextPrefix: "La verdad permanece oculta: ",
    allRevealedTitle: "✦ Todos los Secretos Revelados ✦",
    allRevealedText: "Has descubierto todas las verdades... por ahora.",

  }
};

export const questionsEn = [
  { id: 1, question: "Who truly pulls the strings from the shadows?", answer: "Illuminati" },
  { id: 2, question: "What really crashed in Roswell in '47?", answer: "Alien craft" },
  { id: 3, question: "Who directed the moon landing hoax?", answer: "Kubrick" },
  { id: 4, question: "What was the CIA's mind control program called?", answer: "MKUltra" },
  { id: 5, question: "What are the Guidestones' true purpose?", answer: "Population control" },
  { id: 6, question: "Who meets in secret to plan our fate?", answer: "Bilderberg Group" },
  { id: 7, question: "What do the trails in the sky spread?", answer: "Chemtrails" },
  { id: 8, question: "Who is the anonymous prophet 'Q'?", answer: "Military intelligence" },
  { id: 9, question: "What hidden race rules from above?", answer: "Reptilians" },
  { id: 10, question: "What is the ultimate goal of the elite?", answer: "New World Order" },
  { id: 11, question: "What lies beneath the Denver Airport?", answer: "Underground bunker" },
  { id: 12, question: "Who controls the world's finances?", answer: "Rothschilds" },
  { id: 13, question: "What secret society rules the USA?", answer: "Skull and Bones" },
  { id: 14, question: "What event was a false flag operation?", answer: "9/11" },
  { id: 15, question: "What is HAARP's true function?", answer: "Weather weapon" },
  { id: 16, question: "What do they put in our water?", answer: "Fluoride" },
  { id: 17, question: "Who really killed JFK?", answer: "The CIA" },
  { id: 18, question: "What lies in Area 51?", answer: "UFO technology" },
  { id: 19, question: "What is the purpose of FEMA camps?", answer: "Mass imprisonment" },
  { id: 20, question: "Who are the 'Men in Black'?", answer: "Silencing agents" },
  { id: 21, question: "What did the Vatican hide?", answer: "Ancient texts" },
  { id: 22, question: "What is the goal of The Great Reset?", answer: "Total control" },
  { id: 23, question: "What is in the vaccines?", answer: "Microchips" },
  { id: 24, question: "Who are the global puppet masters?", answer: "The Cabal" },
  { id: 25, question: "What lies at the Earth's core?", answer: "Hollow Earth" },
  { id: 26, question: "Who built the pyramids?", answer: "Ancient aliens" },
  { id: 27, question: "What do the elites practice in secret?", answer: "Satanic rituals" },
  { id: 28, question: "What is Project Blue Beam?", answer: "Fake alien invasion" },
  { id: 29, question: "What is the true nature of reality?", answer: "A simulation" },
  { id: 30, question: "What do the world leaders worship?", answer: "The owl god" },
  { id: 31, question: "What is the secret of the moon?", answer: "It's artificial" },
  { id: 32, question: "Who guards the bloodlines?", answer: "The Priory" },
  { id: 33, question: "What is the final truth?", answer: "We are slaves" }
];

export const questionsEs = [
  { id: 1, question: "¿Quién mueve los hilos desde las sombras?", answer: "Iluminados" },
  { id: 2, question: "¿Qué cayó realmente en Roswell en '47?", answer: "Nave alienígena" },
  { id: 3, question: "¿Quién dirigió el fraude del alunizaje?", answer: "Kubrick" },
  { id: 4, question: "¿Cómo se llamaba el programa de control mental de la CIA?", answer: "MKUltra" },
  { id: 5, question: "¿Cuál es el verdadero propósito de las Guidestones?", answer: "Control poblacional" },
  { id: 6, question: "¿Quién se reúne en secreto para planificar nuestro destino?", answer: "Grupo Bilderberg" },
  { id: 7, question: "¿Qué dispersan los rastros en el cielo?", answer: "Quimtrails" },
  { id: 8, question: "¿Quién es el profeta anónimo 'Q'?", answer: "Inteligencia militar" },
  { id: 9, question: "¿Qué raza oculta gobierna desde las alturas?", answer: "Reptilianos" },
  { id: 10, question: "¿Cuál es el objetivo final de la élite?", answer: "Nuevo Orden Mundial" },
  { id: 11, question: "¿Qué hay debajo del Aeropuerto de Denver?", answer: "Búnker subterráneo" },
  { id: 12, question: "¿Quién controla las finanzas del mundo?", answer: "Rothschild" },
  { id: 13, question: "¿Qué sociedad secreta gobierna EE.UU.?", answer: "Cráneo y Huesos" },
  { id: 14, question: "¿Qué evento fue una operación de falsa bandera?", answer: "11-S" },
  { id: 15, question: "¿Cuál es la verdadera función de HAARP?", answer: "Arma climática" },
  { id: 16, question: "¿Qué nos echan en el agua?", answer: "Flúor" },
  { id: 17, question: "¿Quién mató realmente a JFK?", answer: "La CIA" },
  { id: 18, question: "¿Qué hay en el Área 51?", answer: "Tecnología OVNI" },
  { id: 19, question: "¿Cuál es el propósito de los campos de FEMA?", answer: "Encarcelamiento masivo" },
  { id: 20, question: "¿Quiénes son los 'Hombres de Negro'?", answer: "Agentes silenciadores" },
  { id: 21, question: "¿Qué ocultó el Vaticano?", answer: "Textos antiguos" },
  { id: 22, question: "¿Cuál es el objetivo del Gran Reinicio?", answer: "Control total" },
  { id: 23, question: "¿Qué hay en las vacunas?", answer: "Microchips" },
  { id: 24, question: "¿Quiénes son los titiriteros globales?", answer: "La Cábala" },
  { id: 25, question: "¿Qué hay en el núcleo de la Tierra?", answer: "Tierra hueca" },
  { id: 26, question: "¿Quién construyó las pirámides?", answer: "Aliens antiguos" },
  { id: 27, question: "¿Qué practican las élites en secreto?", answer: "Rituales satánicos" },
  { id: 28, question: "¿Qué es el Proyecto Blue Beam?", answer: "Invasión alienígena falsa" },
  { id: 29, question: "¿Cuál es la verdadera naturaleza de la realidad?", answer: "Una simulación" },
  { id: 30, question: "¿Qué adoran los líderes mundiales?", answer: "El dios búho" },
  { id: 31, question: "¿Cuál es el secreto de la Luna?", answer: "Es artificial" },
  { id: 32, question: "¿Quién protege las líneas de sangre?", answer: "La Prieuré" },
  { id: 33, question: "¿Cuál es la verdad final?", answer: "Somos esclavos" }
];
