export const products = [
  {
    id: 1,
    name: "Pizza",
    description: "Classic pizza with tomato sauce, mozzarella cheese, and fresh basil.",
    image: "./images/products/pizza.png",
    minPrice: 500,
    maxPrice: 2500,
  },
  {
    id: 2,
    name: "Hot Dog",
    description: "Juicy beef patty with lettuce, tomato, and cheese on a sesame bun.",
    image: "./images/products/hot-dog.png",
    minPrice: 300,
    maxPrice: 1500,
  },
  {
    id: 3,
    name: "Cheese",
    description: "Fresh cheese with a variety of flavors, including cheddar, mozzarella, and gouda.",
    image: "./images/products/cheese.png",
    minPrice: 800,
    maxPrice: 3500,
  },
  {
    id: 4,
    name: "Pasta",
    description: "Delicious pasta dishes with a variety of sauces, including marinara, alfredo, and pesto.",
    image: "./images/products/pasta.png",
    minPrice: 400,
    maxPrice: 1800,
  },
  {
    id: 5,
    name: "Ice Cream",
    description: "Creamy ice cream in a variety of flavors, including chocolate, vanilla, and strawberry.",
    image: "./images/products/ice-cream.png",
    minPrice: 200,
    maxPrice: 1000,
  },
  {
    id: 6,
    name: "Walnut",
    description: "Delicious walnuts with a variety of flavors, including roasted, salted, and honey-glazed.",
    image: "./images/products/walnut.png",
    minPrice: 350,
    maxPrice: 1200,
  },
]
